#include <stdio.h>

int main()  {


// so yeah this is a small cheap version forgive my laziness. but this is a %S %S structure where you can do %S %S %S %S %S x10 x 20 what ever. and do embedded files instead of CHAR * 
// uhm yeah email me back patrickbrycemooney@gmail.com if you want to talk about the whole 100k 100k 100k %S %S %S for uhm sec groups, SEC people and sec tools, programs, products, etc.
// thee uhm linux.org SAIDDD this could be a structure to end all evil! use GEN ai LLM to populate ALL values. out there... could be pretty cool guys! PLEASE PLEASE PLEASE give me an 
  // email back out of your busy day... even if you think im a hack! i want to connect with a real live linux engineer. hear how goofy i look and sound... i really like security and linux
  // so please help me find my little home with the linux security fraternity and sorority of linux goodness... <3     (:    😁⚔️🧙‍♂️



char* good_religious_leaders[100] = {
    "1. Pope Francis (Catholicism)",
    "2. Dalai Lama (Tibetan Buddhism)",
    "3. Desmond Tutu (Anglican, South Africa, †2021)",
    "4. Thich Nhat Hanh (Zen Buddhism, †2022)",
    "5. Dr. Rowan Williams (Former Archbishop of Canterbury)",
    "6. Patriarch Bartholomew I (Eastern Orthodox Church)",
    "7. Rabbi Jonathan Sacks (Judaism, †2020)",
    "8. Shaykh Hamza Yusuf (Islam, USA)",
    "9. Sister Helen Prejean (Catholic nun and anti-death penalty advocate)",
    "10. Swami Sivananda (Yoga and Hinduism)",
    "11. Sri Sri Ravi Shankar (Hinduism, Art of Living Foundation)",
    "12. Amma (Mata Amritanandamayi, Hindu spiritual leader)",
    "13. Rabbi Abraham Skorka (Judaism, Argentina)",
    "14. Mufti Menk (Islam, Zimbabwe)",
    "15. Bhikkhu Bodhi (American Theravada monk and translator)",
    "16. Thomas Keating (Christian monk, †2018)",
    "17. Sadhvi Bhagawati Saraswati (Hinduism)",
    "18. Rabbi Jill Jacobs (Judaism, USA)",
    "19. Imam Omar Suleiman (Islam, USA)",
    "20. Bishop Michael Curry (Episcopal Church, USA)",
    "21. Sheikh Abdallah bin Bayyah (Islam, Mauritania)",
    "22. Rabbi David Rosen (Judaism, interfaith leader)",
    "23. Dr. Ingrid Mattson (Islamic scholar, Canada)",
    "24. John Dear (Catholic priest, peace activist)",
    "25. Eboo Patel (Interfaith Youth Core, Islam, USA)",
    "26. Rabbi Sharon Brous (IKAR, Judaism, USA)",
    "27. Sheikh Yasir Qadhi (Islamic scholar, USA)",
    "28. Satish Kumar (Jainism, India)",
    "29. Rev. James Lawson (Christian nonviolence leader)",
    "30. Gyalwang Drukpa (Drukpa Lineage of Tibetan Buddhism)",
    "31. Archbishop Justin Welby (Church of England)",
    "32. Cardinal Tagle (Catholic, Philippines)",
    "33. Sri Prem Baba (Hindu/Brazilian spiritual leader)",
    "34. Rabbi Arthur Waskow (Judaism, USA)",
    "35. Rev. Dr. William Barber II (Christianity, USA)",
    "36. Sister Joan Chittister (Catholic nun and author)",
    "37. Rabbi Zalman Schachter-Shalomi (Jewish Renewal, †2014)",
    "38. Fr. Richard Rohr (Franciscan priest, USA)",
    "39. Sheikh Abdullah Kamal (Islam, Egypt, †2015)",
    "40. Mahant Swami Maharaj (BAPS, Hinduism)",
    "41. Ven. Ajahn Sumedho (Theravada monk, UK)",
    "42. Ven. Pannavati Bhikkhuni (Buddhism, USA)",
    "43. Bhai Sahib Mohinder Singh (Sikh, UK)",
    "44. Jaggi Vasudev (Sadhguru, Isha Foundation)",
    "45. Swami Avdheshanand Giri (Hinduism, India)",
    "46. Tenzin Palmo (Buddhist nun, UK)",
    "47. Syed Hossein Nasr (Islamic scholar, Iran/USA)",
    "48. Imam Zaid Shakir (Islam, USA)",
    "49. Rev. Nadia Bolz-Weber (Christian Lutheran, USA)",
    "50. Rabbi Danya Ruttenberg (Judaism, USA)",
    "51. Dr. Sayyid M. Syeed (Islamic Society of North America)",
    "52. Ayya Khema (Buddhism, †1997)",
    "53. Bhante Gunaratana (Sri Lankan Buddhist monk, USA)",
    "54. Pastor Rick Warren (Christianity, USA)",
    "55. Pastor Francis Chan (Christianity, USA)",
    "56. Rev. Greg Boyle (Jesuit priest, Homeboy Industries)",
    "57. Ven. Henepola Gunaratana (Theravada Buddhism, Sri Lanka)",
    "58. Sheikh Mokhtar Maghraoui (Islam, Algeria/USA)",
    "59. Archbishop Wilton Gregory (Catholic, USA)",
    "60. Dr. Amina Wadud (Islamic feminist scholar)",
    "61. Rabbi Menachem Froman (Judaism, †2013)",
    "62. Sheikh Nazim al-Haqqani (Sufi Islam, †2014)",
    "63. Sri Chinmoy (Hindu/Yoga, †2007)",
    "64. Brother David Steindl-Rast (Catholic monk)",
    "65. Rabbi Rami Shapiro (Judaism, interfaith author)",
    "66. Rev. Karen Georgia Thompson (United Church of Christ)",
    "67. Archbishop Desmond Mpilo Tutu Jr. (Anglican Church, South Africa)",
    "68. Rabia Terri Harris (Sufi Muslim chaplain)",
    "69. Dr. Reza Aslan (Islamic scholar, USA)",
    "70. Master Cheng Yen (Buddhism, Taiwan)",
    "71. Guru Granth Sahib Ji (Sikh scripture—unified spiritual authority)",
    "72. Rabbi Chaim Miller (Judaism, Chabad)",
    "73. Sister Teresa Forcades (Benedictine nun, Spain)",
    "74. Sheikh Abdul Hakim Murad (Tim Winter, UK Islamic scholar)",
    "75. Hozan Alan Senauke (Buddhist, USA)",
    "76. Sister Jeannine Gramick (Catholic nun, LGBT rights)",
    "77. Pastor Brian Zahnd (Christianity, USA)",
    "78. Rabbi Brad Hirschfield (Jewish interfaith leader)",
    "79. Sheikh Nuh Keller (Sufi Islam, Jordan)",
    "80. Bishop Thomas Gumbleton (Catholic peace activist)",
    "81. Sri M (Mumtaz Ali, Hindu mystic)",
    "82. Rabbi Adin Steinsaltz (Judaism, †2020)",
    "83. Imam Khalid Latif (Islam, USA)",
    "84. Rabbi Laura Geller (Judaism, USA)",
    "85. Archbishop Hélder Câmara (Catholic, Brazil, †1999)",
    "86. Rabbi Angela Buchdahl (Judaism, USA)",
    "87. Sr. Simone Campbell (Catholic nun and social justice activist)",
    "88. Sheikh Hisham Kabbani (Sufi Islam, USA)",
    "89. Swami Tejomayananda (Hindu, Chinmaya Mission)",
    "90. Ven. Robina Courtin (Buddhist nun, Australia)",
    "91. Patriarch Ignatius Aphrem II (Syriac Orthodox Church)",
    "92. Rabbi Yosef Kanefsky (Judaism, USA)",
    "93. Sheikh Saad Nomani (Qur'an reciter, Saudi Arabia)",
    "94. Pastor Rob Bell (Christian, USA)",
    "95. Pastor Eugene Cho (Christianity, USA)",
    "96. Rev. Dr. Jacqui Lewis (Christianity, USA)",
    "97. Rabbi Shai Held (Judaism, USA)",
    "98. Dr. Alaa Murabit (Islamic feminist, Libya/Canada)",
    "99. Fr. Gustavo Gutiérrez (Catholic liberation theologian, Peru)",
    "100. Sheikh Imran N. Hosein (Islamic eschatologist, Trinidad)"
};

    
 // List of national security groups
    char* national_sec[782] = {



"National Security Agency (NSA) - United States", "Federal Bureau of Investigation (FBI) - United States", 
"Cybersecurity and Infrastructure Security Agency (CISA) - United States", "Government Communications Headquarters (GCHQ) - United Kingdom", 
"National Cyber Security Centre (NCSC) - United Kingdom", "Australian Cyber Security Centre (ACSC) - Australia", 
"European Union Agency for Cybersecurity (ENISA) - European Union", "Canadian Centre for Cyber Security (CCCS) - Canada", 
"Cyber Command - United States", "National Cybersecurity and Communications Integration Center (NCCIC) - United States", 
"Ministry of Defense Cyber Command - United Kingdom", "Ministry of the Interior and Kingdom Relations - Netherlands", 
"Cybersecurity and Information Security Agency - Singapore", "Cyber Security Agency of Singapore (CSA) - Singapore", 
"National Cyber Security Directorate - Portugal", "Central Cybersecurity Agency - France", 
"Federal Office for Information Security (BSI) - Germany", "National Cybersecurity Authority - Israel", 
"Department of Homeland Security (DHS) - United States", "National Cybersecurity Agency - France", 
"Security Service of Ukraine - Ukraine", "National Cyber Security Agency - South Korea", 
"Federal Security Service (FSB) - Russia", "National Cyber Intelligence Center - Belgium", 
"Cybercrime Unit - INTERPOL", "National Cyber Security Centre - New Zealand", 
"Cyber Security Bureau - Taiwan", "Cyber Security Center - India", 
"Swedish Civil Contingencies Agency (MSB) - Sweden", "Cyber Security Agency - Malaysia", 
"National Cyber Security Authority - Denmark", "Cyber Security Operations Center - Estonia", 
"Cyber Defence Command - South Korea", "National Cyber Security Center - Ireland", 
"General Directorate of Security - Turkey", "Federal Bureau of Cyber Security - Brazil", 
"Cyber Security Division - Japan", "Cyber Security Center - Saudi Arabia", 
"National Cyber Security Center - South Africa", "Cybersecurity Operations Center - Finland", 
"National Cybersecurity Coordination Center - Netherlands", "Cyber Defense Operations Center - Canada", 
"National Cyber Security Authority - Spain", "National Cyber Coordination Center - India", 
"Cyber Security and Cyber Crime Investigation Cell - India", "National Information Security Center - Indonesia", 
"National Cyber Security Center - Qatar", "Cyber Security Center - Argentina", 
"Department of Digital, Culture, Media and Sport (DCMS) - United Kingdom", "Ministry of Interior - Italy", 
"Federal Department of Justice and Police - Switzerland", "National Cybersecurity Center - UAE", 
"National Cyber Security Center - Iceland", "Ministry of Defense Cyber Defense Agency - Norway", 
"Cyber Security Center - Russia", "Intelligence Bureau Cyber Cell - India", 
"Cyber Security Division - Australia", "Department of Defense - Cyber Strategy Office - United States", 
"Federal Office of Communications - Switzerland", "Cyber Security and Critical Infrastructure - France", 
"National Cyber Security Center - Luxembourg", "Cyber Defense Unit - Philippines", 
"National Cyber Security Agency - Greece", "National Cyber Security Center - Bahrain", 
"Cyber Security Command - Malaysia", "Cybersecurity and Communication Security Agency - Japan", 
"National Cyber Security Directorate - Chile", "National Cyber Security Authority - Hungary", 
"Cyber Security Division - South Africa", "Cyber Security Operations Center - Tunisia", 
"National Cybersecurity Center - Vietnam", "National Cyber Security Center - Colombia", 
"Cyber Intelligence Unit - Ukraine", "National Cyber Security Center - Morocco", 
"National Cyber Security Center - Singapore", "Cyber Security Division - Kenya", 
"Cyber Security Authority - Jamaica", "Cybersecurity Agency - Ghana", 
"Cyber Security Center - Zimbabwe", "Cyber Security Division - Tanzania", 
"Cyber Security Unit - Nigeria", "Cyber Security Center - Bangladesh", 
"Cyber Defense Agency - Sri Lanka", "National Cyber Security Center - Algeria", 
"Cyber Security Bureau - Mongolia", "Cyber Security Center - Myanmar", 
"Cybersecurity Agency - Ethiopia", "Cyber Security Unit - South Sudan",


"National Cyber Security Centre - Lithuania", "National Cyber Security Agency - Armenia", 
"Federal Cyber Security Office - Germany", "Cyber Security Operations Center - Brazil", 
"Cybersecurity Bureau - Thailand", "Cyber Defence and Security Agency - Finland", 
"National Computer Security Center - Russia", "Cyber Security Division - Chile", 
"Cyber Security Council - Bangladesh", "National Cyber Security Division - South Korea", 
"Cybersecurity and Privacy Office - United States", "National Cyber Security Office - Ghana", 
"Cyber Intelligence Agency - Canada", "Digital Security Agency - Netherlands", 
"Information Security Agency - Italy", "Cyber Security Division - Mexico", 
"National Cyber Security Agency - Luxembourg", "Government Cyber Security Centre - Ukraine", 
"Information Assurance Division - Australia", "Cybersecurity Division - Kazakhstan", 
"Cyber Defense Centre - Sweden", "Cyber Security Group - Estonia", 
"Cyber Operations Center - United Arab Emirates", "Cyber Crime Agency - Cyprus", 
"Office of Cybersecurity - Indonesia", "Cyber Safety Agency - New Zealand", 
"Cyber Security Commission - Spain", "Cyber Defense Directorate - France", 
"National Cyber Security Authority - Morocco", "Cyber Risk Management Agency - Singapore", 
"Cyber Operations Bureau - Thailand", "Cyber Threat Intelligence Center - Philippines", 
"Cyber Security Institute - Denmark", "Office of Cybersecurity - Bahrain", 
"Cyber Security Task Force - South Africa", "Cyber Defense Strategy Office - Switzerland", 
"National Cyber Intelligence Office - UAE", "Cyber Security Division - Norway", 
"Cyber Safety Division - Malaysia", "Cyber Security Bureau - Iraq", 
"Cyber Protection Agency - Japan", "Cyber Security Division - Sri Lanka", 
"Cyber Intelligence and Security Agency - Nigeria", "Cyber Security Office - Peru", 
"National Cybersecurity Division - Paraguay", "Cyber Defense Agency - Kosovo", 
"Cyber Risk Mitigation Agency - Romania", "Cyber Security and Infrastructure Agency - Philippines", 
"National Cyber Response Team - New Zealand", "Cyber Security Directorate - Hungary", 
"Cyber Operations Command - Georgia", "Cyber Security Division - Kazakhstan", 
"Cyber Intelligence Directorate - Italy", "National Cyber Defense Center - Lebanon", 
"Cyber Protection Division - Bangladesh", "National Cyber Safety Agency - Malta", 
"Cyber Defense Unit - Zimbabwe", "Cyber Security Enforcement Agency - Venezuela", 
"Cyber Safety Directorate - Qatar", "Cyber Crime Prevention Division - Uganda", 
"Cyber Threat Response Center - Tunisia", "Cyber Defense Bureau - Malta", 
"Cyber Security Operations Center - Ethiopia", "Cyber Defense Coordination Agency - South Korea", 
"Cyber Security Task Force - Sudan", "Cyber Security Intelligence Bureau - Liberia", 
"National Information Protection Agency - Bhutan", "Cyber Security Control Centre - Belarus", 
"National Cyber Threat Centre - Singapore", "Cybersecurity Response Taskforce - Peru", 
"Cyber Operations Command - Mongolia", "Cyber Security Group - Portugal", 
"National Cyber Security Board - Sri Lanka", "Cyber Intelligence Division - Nigeria", 
"Cyber Protection Force - El Salvador", "Cyber Defense and Protection Unit - Cambodia", 
"Cyber Risk Assessment Agency - Nicaragua", "Cyber Security and Intelligence Agency - Kenya", 
"Cyber Defense Coordination Centre - Uruguay", "Cyber Security Task Group - Paraguay", 
"Cyber Threat Assessment Office - Madagascar", "National Cyber Safety Taskforce - Belize", 
"Cyber Protection Directorate - Haiti", "Cyber Intelligence Operations Unit - Sri Lanka", 
"Cyber Defense Security Council - Bosnia and Herzegovina", "Cyber Protection Bureau - Dominican Republic", 
"Cyber Security and Risk Agency - Togo", "Cyber Intelligence Centre - Kyrgyzstan", 
"Cyber Security Directorate - Uzbekistan", "National Cyber Threat Center - Barbados", 
"Cyber Security Unit - Suriname", "Cyber Protection Agency - Zimbabwe", 
"Cyber Security Strategy Office - Albania", "Cyber Defense Coordination Unit - Moldova",






// biggest south american cyber defense division 


"1. Agência Brasileira de Inteligência (ABIN) - Brazil",  
"2. Departamento de Segurança da Informação (DSI) - Brazil",  
"3. Centro de Defesa Cibernética (CDC) - Brazil",  
"4. Agência Nacional de Telecomunicações (ANATEL) - Brazil",  
"5. Secretaría de Innovación y Gobierno Abierto - Argentina",  
"6. Agencia de Administración de Tecnologías de la Información y las Comunicaciones (AATIC) - Argentina",  
"7. Dirección Nacional de Ciberseguridad - Argentina",  
"8. Centro de Respuesta a Incidentes de Seguridad Informática (CERT) - Argentina",  
"9. Ministerio de Defensa - Chile",  
"10. Centro Nacional de Ciberseguridad (CNCS) - Chile",  
"11. Policía de Investigaciones de Chile (PDI) - Chile",  
"12. Agencia de Seguridad y Ciberinteligencia (ASI) - Colombia",  
"13. Ministerio de Tecnologías de la Información y las Comunicaciones (MinTIC) - Colombia",  
"14. Centro Cibernético Policial - Colombia",  
"15. Unidad de Investigación de Delitos Informáticos - Colombia",  
"16. Agencia de Seguridad Nacional - Uruguay",  
"17. Centro de Respuesta a Incidentes de Seguridad Informática (CERT) - Uruguay",  
"18. Ministerio del Interior - Paraguay",  
"19. Centro Nacional de Ciberseguridad - Paraguay",  
"20. Secretaría Nacional de Ciberseguridad - Paraguay",  
"21. Dirección de Ciberseguridad - Ecuador",  
"22. Agencia Nacional de Regulación, Control y Fiscalización Sanitaria (ARCSA) - Ecuador",  
"23. Policía Nacional del Ecuador - Ecuador",  
"24. Centro de Ciberseguridad - Bolivia",  
"25. Unidad de Cibercrimen - Bolivia",  
"26. Ministerio de Obras Públicas, Servicios y Vivienda - Bolivia",  
"27. Ministerio de Defensa - Venezuela",  
"28. Centro de Ciberseguridad - Venezuela",  
"29. Comisión Nacional de Telecomunicaciones (CONATEL) - Venezuela",  
"30. Secretaría de Seguridad Pública y Justicia - Brazil",  
"31. Comando de Defesa Cibernética - Brazil",  
"32. Centro de Ciberseguridad - Chile",  
"33. Servicio Nacional de Aprendizaje (SENA) - Colombia",  
"34. Dirección de Análisis de Ciberinteligencia - Argentina",  
"35. Ministerio de Educación - Uruguay",  
"36. Secretaría de Tecnología de la Información y Comunicación (STIC) - Paraguay",  
"37. Fiscalía General del Estado - Ecuador",  
"38. Centro de Operaciones de Seguridad Cibernética (SOC) - Brazil",  
"39. Dirección Nacional de Protección de Datos Personales - Argentina",  
"40. Subsecretaría de Ciberseguridad - Chile",  
"41. Centro de Ciberinteligencia - Colombia",  
"42. Secretaría de Seguridad Pública - Mexico",  
"43. Policía Nacional - Bolivia",  
"44. Policía Federal - Argentina",  
"45. Servicio Nacional de Inteligencia (SENAIN) - Ecuador",  
"46. Agencia Nacional de Ciberseguridad - Colombia",  
"47. Centro Nacional de Seguridad de Ciberespacio - Venezuela",  
"48. Unidad Cibernética - Paraguay",  
"49. Subsecretaría de Inteligencia Estratégica del Estado - Argentina",  
"50. Ministerio de Comunicación e Información - Venezuela",  
"51. Secretaría de Seguridad Pública - Uruguay",  
"52. División de Delitos Cibernéticos - Chile",  
"53. Servicio de Inteligencia - Bolivia",  
"54. Coordinación de Ciberseguridad - Paraguay",  
"55. Agencia de Seguridad Nacional - Ecuador",  
"56. Dirección de Ciberseguridad y Telecomunicaciones - Brazil",  
"57. Centro de Gestión de Seguridad de la Información - Argentina",  
"58. Instituto Nacional de Tecnología - Uruguay",  
"59. Dirección Nacional de Ciberinteligencia - Chile",  
"60. Secretaría de Ciberseguridad - Colombia",  
"61. Policía de Seguridad Aeroportuaria - Argentina",  
"62. Agencia de Seguridad Cibernética - Bolivia",  
"63. Secretaría de Política Criminal - Uruguay",  
"64. Dirección de Seguridad de la Información - Venezuela",  
"65. Centro de Protección de Infraestructuras Críticas - Brazil",  
"66. Fiscalía de Cibercrimen - Colombia",  
"67. Centro de Estudios de Ciberseguridad - Chile",  
"68. Unidad de Ciberseguridad - Paraguay",  
"69. Unidad de Inteligencia de Cibercrimen - Argentina",  
"70. Ministerio de Relaciones Exteriores - Brazil",  
"71. Unidad Nacional de Delitos Cibernéticos - Bolivia",  
"72. Dirección de Seguridad Pública - Ecuador",  
"73. Coordinación de Análisis de Ciberseguridad - Uruguay",  
"74. Servicio de Inteligencia - Chile",  
"75. Agencia Nacional de Defensa - Venezuela",  
"76. Subdirección de Ciberseguridad - Colombia",  
"77. Centro Nacional de Monitoreo Cibernético - Brazil",  
"78. Oficina de Ciberseguridad - Ecuador",  
"79. Ministerio de Seguridad - Argentina",  
"80. Unidad de Investigación y Análisis Cibernético - Bolivia",  
"81. Centro de Información y Comunicación - Paraguay",  
"82. Dirección de Análisis y Protección de Datos - Chile",  
"83. Agencia de Proyectos Estratégicos - Colombia",  
"84. Centro de Información sobre Amenazas Cibernéticas - Venezuela",  
"85. Comisión de Seguridad y Defensa - Ecuador",  
"86. Ministerio de Defensa y Ciberseguridad - Uruguay",  
"87. Oficina de Seguridad de la Información - Bolivia",  
"88. Subsecretaría de Seguridad y Protección de Datos - Argentina",  
"89. División de Delitos Tecnológicos - Brazil",  
"90. Unidad de Ciberseguridad de la Defensa - Chile",  
"91. Centro Nacional de Respuesta a Incidentes de Ciberseguridad - Colombia",  
"92. Dirección de Seguridad de la Información y Ciberseguridad - Paraguay",  
"93. Policía Nacional de Ciberseguridad - Venezuela",  
"94. Centro de Coordinación de Ciberseguridad - Uruguay",  
"95. Comisión de Ciberseguridad - Ecuador",  
"96. Unidad de Ciberinteligencia y Delitos Electrónicos - Bolivia",  
"97. Centro de Resiliencia Cibernética - Argentina",  
"98. Secretaría de Seguridad - Chile",  
"99. Ministerio de Seguridad y Ciberseguridad - Colombia",  
"100. Dirección de Protección de Infraestructura Crítica - Brazil",






// australlian biggest govt cyber defense team 


"1. Australian Cyber Security Centre (ACSC)",  
"2. Australian Signals Directorate (ASD)",  
"3. Department of Home Affairs",  
"4. Australian Federal Police (AFP)",  
"5. Department of Defence",  
"6. Cyber Security Coordination Unit",  
"7. Cyber Security Policy and Strategy Division",  
"8. Office of the Cyber Security Commissioner",  
"9. Australian Criminal Intelligence Commission (ACIC)",  
"10. Australian Security Intelligence Organisation (ASIO)",  
"11. National Cyber Security Strategy Team",  
"12. Cyber Operations Branch - ASD",  
"13. Defence Intelligence Organisation (DIO)",  
"14. Department of the Prime Minister and Cabinet",  
"15. Cyber Security Incident Response Team (CSIRT)",  
"16. Digital Transformation Agency (DTA)",  
"17. Australian Transaction Reports and Analysis Centre (AUSTRAC)",  
"18. Cyber Security Workforce Development Program",  
"19. National Security Division - Department of Home Affairs",  
"20. Critical Infrastructure Centre - Home Affairs",  
"21. Digital Security Division - Department of Defence",  
"22. Cyber Security Engagement Team",  
"23. Protective Security Policy Framework - Australian Government",  
"24. Cyber Threat Intelligence Team - ASD",  
"25. Cyber Security Research Program",  
"26. National Cyber Security Centre",  
"27. Cyber Security Risk Assessment Program",  
"28. National Digital Asset Management Team",  
"29. Cyber Security Awareness and Education Program",  
"30. Cyber Security Capability Improvement Program",  
"31. International Cyber Policy Team - DFAT",  
"32. Cyber Security Operations Centre - ASD",  
"33. Cyber Security Resilience Program",  
"34. Digital Identity Program",  
"35. Cyber Security Framework Development Team",  
"36. Cyber Security Procurement Program",  
"37. Cyber Security Compliance and Assurance Team",  
"38. National ICT Security Strategy Team",  
"39. Cyber Security Governance Group",  
"40. Cyber Security Capability Development Team",  
"41. Australian Government Computer Emergency Response Team (AusCERT)",  
"42. Cyber Security Policy Implementation Team",  
"43. Cyber Security Testing and Assurance Team",  
"44. Cyber Security Incident Management Team",  
"45. Cyber Security Risk Management Team",  
"46. Cyber Security Awareness Campaign Team",  
"47. National Cyber Threat Sharing Program",  
"48. Cyber Security Skills Development Team",  
"49. Cyber Security Analysis and Reporting Team",  
"50. Cyber Security Investigation Team - AFP",  
"51. Cyber Security Policy Advisory Committee",  
"52. Cyber Security Communications Team",  
"53. Cyber Security Data Analytics Team",  
"54. Cyber Security Project Management Office",  
"55. Cyber Security Operations Planning Team",  
"56. Cyber Security Research and Development Team",  
"57. Cyber Security Standards Development Team",  
"58. Cyber Security Incident Reporting Team",  
"59. Cyber Security Compliance Monitoring Team",  
"60. Cyber Security Capability Assessment Team",  
"61. Cyber Security Exercise and Simulation Team",  
"62. Cyber Security Incident Response Exercise Team",  
"63. Cyber Security Strategic Partnerships Team",  
"64. Cyber Security Outreach and Engagement Team",  
"65. Cyber Security Governance and Compliance Team",  
"66. Cyber Security Technology Development Team",  
"67. Cyber Security Framework Review Team",  
"68. Cyber Security Implementation Team",  
"69. Cyber Security Audit and Assurance Team",  
"70. Cyber Security Risk and Resilience Team",  
"71. Cyber Security Community Engagement Team",  
"72. Cyber Security Coordination and Collaboration Team",  
"73. Cyber Security Capability Building Team",  
"74. Cyber Security Intelligence Analysis Team",  
"75. Cyber Security Policy Research Team",  
"76. Cyber Security Information Sharing Team",  
"77. Cyber Security Threat Analysis Team",  
"78. Cyber Security Regulatory Compliance Team",  
"79. Cyber Security Innovation and Development Team",  
"80. Cyber Security Public Awareness Team",  
"81. Cyber Security Interagency Coordination Team",  
"82. Cyber Security Workforce Strategy Team",  
"83. Cyber Security Legal and Policy Team",  
"84. Cyber Security Industry Engagement Team",  
"85. Cyber Security Incident Response Planning Team",  
"86. Cyber Security Technology Advisory Team",  
"87. Cyber Security Data Governance Team",  
"88. Cyber Security Supply Chain Risk Management Team",  
"89. Cyber Security Knowledge Management Team",  
"90. Cyber Security Policy Development Team",  
"91. Cyber Security National Framework Team",  
"92. Cyber Security Professional Development Team",  
"93. Cyber Security Continuous Improvement Team",  
"94. Cyber Security Communication Strategy Team",  
"95. Cyber Security Incident Recovery Team",  
"96. Cyber Security Program Management Office",  
"97. Cyber Security Vulnerability Management Team",  
"98. Cyber Security Service Delivery Team",  
"99. Cyber Security Collaboration Network",  
"100. Cyber Security Operational Readiness Team",






// biggest asian cyber defence teams

"1. Cybersecurity Agency of Singapore (CSA) - Singapore",  
"2. National Cyber Security Centre (NCSC) - United Kingdom (Asia-Pacific operations)",  
"3. Ministry of Electronics and Information Technology (MeitY) - India",  
"4. Computer Emergency Response Team - India (CERT-IN)",  
"5. National Cyber Security Agency (NCSA) - South Korea",  
"6. Cyber Command - South Korea",  
"7. Ministry of Information and Communications - Vietnam",  
"8. Vietnam Cyber Security Emergency Response Teams (VNCERT)",  
"9. National Cyber Security Center - Malaysia",  
"10. CyberSecurity Malaysia - Malaysia",  
"11. Cyber Security Division - Philippines",  
"12. Department of Information and Communications Technology (DICT) - Philippines",  
"13. Cyber Security and Information Security Agency - Thailand",  
"14. National Cybersecurity Agency of Japan (NCA) - Japan",  
"15. Japan Computer Emergency Response Team Coordination Center (JPCERT/CC) - Japan",  
"16. Ministry of Digital Economy and Society - Thailand",  
"17. Cyber Crime Investigation Bureau - Thailand",  
"18. Cyber Security Directorate - Pakistan",  
"19. Pakistan Computer Emergency Response Team (PakCERT)",  
"20. National Information Technology Development Agency (NITDA) - Nigeria (with Asian collaboration)",  
"21. National Institute of Standards and Technology - USA (Asia operations)",  
"22. Cybersecurity Task Force - Taiwan",  
"23. National Cybersecurity Center - Taiwan",  
"24. Cybersecurity and Infrastructure Security Agency - USA (Asia operations)",  
"25. Ministry of Public Security - China",  
"26. State Internet Information Office - China",  
"27. National Computer Network Emergency Response Technical Team/Coordination Center of China (CNCERT/CC)",  
"28. China Cybersecurity Review Technology and Certification Center (CCRC)",  
"29. Cyber Security and Digital Crime Center - Saudi Arabia",  
"30. Saudi Arabian Monetary Authority (SAMA) - Cybersecurity Division",  
"31. National Cybersecurity Authority - Bahrain",  
"32. Cyber Security Department - United Arab Emirates",  
"33. Dubai Electronic Security Center - UAE",  
"34. Ministry of Information Technology and Telecommunication - Pakistan",  
"35. National Telecommunications Commission (NTC) - Philippines",  
"36. Cyber Security Branch - Afghanistan",  
"37. Information Security Management Committee - Hong Kong",  
"38. Cyber Security and Information Technology Security Committee - Hong Kong",  
"39. Cybersecurity Division - Singapore Police Force",  
"40. National Cyber Security Policy Council - India",  
"41. Cyber Intelligence Agency - South Korea",  
"42. Central Cyber Security Committee - Thailand",  
"43. Cyber Security and Emergency Response Team - Indonesia",  
"44. Directorate of Information Technology - Nepal",  
"45. National Cyber Security Authority - Israel",  
"46. Israeli National Cyber Directorate",  
"47. Cyber Security Department - Jordan",  
"48. Ministry of Information and Communications - Vietnam",  
"49. Cybersecurity Policy Office - Taiwan",  
"50. Cyber Risk Assessment Unit - Singapore",  
"51. National Security Agency - India",  
"52. Office of Cyber Security - Philippines",  
"53. Cyber Security Research Institute - China",  
"54. Ministry of Defense Cyber Security Agency - Japan",  
"55. National Center for Cyber Security - Pakistan",  
"56. Cyber Intelligence Division - Taiwan",  
"57. Information Security Bureau - Japan",  
"58. Cyber Security Division - Bhutan",  
"59. Cyber Security Regulation Agency - Malaysia",  
"60. Information Security Management Office - Mongolia",  
"61. National Cyber Security Committee - Cambodia",  
"62. Ministry of Digital Economy and Society - Thailand",  
"63. Cyber Crime Division - Afghanistan",  
"64. Cyber Security and Privacy Division - Myanmar",  
"65. Cyber Security Awareness and Training Center - Japan",  
"66. Cyber Security Investigation Bureau - Singapore",  
"67. Cyber Security Command - India",  
"68. Cyber Resilience Institute - South Korea",  
"69. Cyber Defense Command - Japan",  
"70. Information Security Policy Committee - South Korea",  
"71. Cybersecurity Operations Center - Singapore",  
"72. Cyber Threat Intelligence Center - China",  
"73. Cybersecurity Assessment Bureau - Thailand",  
"74. Cyber Protection Unit - Philippines",  
"75. Cyber Security Risk Management Division - Malaysia",  
"76. Cyber Security Research and Development Office - Japan",  
"77. Cyber Security Response Team - Taiwan",  
"78. Cyber Security Training Institute - Pakistan",  
"79. Cyber Security Law Enforcement Agency - India",  
"80. Cyber Security Center for Excellence - Malaysia",  
"81. Cyber Threat Response Center - Indonesia",  
"82. National Cyber Security Monitoring Center - Saudi Arabia",  
"83. Cyber Security Policy and Coordination Center - Afghanistan",  
"84. Cyber Security and Information Security Division - Maldives",  
"85. Cyber Security and Information Assurance Office - Vietnam",  
"86. Cyber Security and Intelligence Coordination Office - Japan",  
"87. National Cyber Security Office - Cambodia",  
"88. Cyber Security Department - Brunei",  
"89. Cyber Defense Coordination Center - Mongolia",  
"90. National Cyber Security Task Force - Singapore",  
"91. Cyber Security and Cybercrime Investigation Unit - India",  
"92. Cyber Security Research and Awareness Division - Taiwan",  
"93. Cyber Security Policy Implementation Unit - Thailand",  
"94. Cyber Security Information Center - Malaysia",  
"95. Cyber Security Oversight Committee - Bangladesh",  
"96. Cyber Security Awareness and Education Bureau - Hong Kong",  
"97. Cybersecurity Incident Response Team - China",  
"98. Cyber Security Compliance Agency - Singapore",  
"99. Cyber Security Strategy Development Office - Vietnam",  
"100. Cyber Security Policy Research Institute - Japan",





// biggest african cyber security teams


"1. South African Cybersecurity Hub - South Africa",  
"2. National Cybersecurity Centre - Nigeria",  
"3. Computer Security Incident Response Team (CSIRT) - Nigeria",  
"4. National Cybersecurity Agency - Kenya",  
"5. Kenya National Computer Incident Response Team Coordination Centre (KE-CIRT/CC) - Kenya",  
"6. Cybersecurity Directorate - Ghana",  
"7. National Cybersecurity Authority - Egypt",  
"8. Computer Emergency Response Team (CERT) - Egypt",  
"9. Ministry of Communications and Digital Technologies - South Africa",  
"10. Cyber Security Division - Botswana",  
"11. National Communications Authority - Ghana",  
"12. Ministry of Information Communication Technology - Uganda",  
"13. Cyber Security and Data Protection Agency - Mozambique",  
"14. National Information Technology Development Agency (NITDA) - Nigeria",  
"15. Cybersecurity Coordination Centre - Algeria",  
"16. National Cybersecurity Agency - Tanzania",  
"17. Cybercrime Investigation Unit - Uganda",  
"18. Ministry of Information - Ethiopia",  
"19. Cyber Security Directorate - Liberia",  
"20. National Cyber Security Authority - Zimbabwe",  
"21. Computer Emergency Response Team (CERT) - Namibia",  
"22. Ministry of Telecommunications and Postal Services - South Africa",  
"23. National Cyber Security Centre - Mali",  
"24. Cybersecurity Division - Zambia",  
"25. Computer Security Incident Response Team (CSIRT) - Cameroon",  
"26. Digital Security and Cybercrime Agency - Morocco",  
"27. National Cybersecurity Task Force - Somalia",  
"28. Cyber Security and Forensics Unit - Rwanda",  
"29. National Cyber Security Center - Sudan",  
"30. Cybercrime Unit - Kenya",  
"31. Cyber Security Department - Sierra Leone",  
"32. National Cybersecurity Council - Tanzania",  
"33. Information Technology Authority - Egypt",  
"34. Cybersecurity Coordination Office - Senegal",  
"35. Cyber Security Unit - Swaziland (Eswatini)",  
"36. National Cyber Security Programme - Tunisia",  
"37. Cyber Security and Information Assurance Agency - Uganda",  
"38. Cyber Intelligence Division - South Africa",  
"39. Ministry of Digital Economy and Society - South Africa",  
"40. Cyber Security Operations Centre - Nigeria",  
"41. Cybersecurity Response Team - Ghana",  
"42. National Cybersecurity Awareness Programme - Botswana",  
"43. National Telecommunications Regulatory Authority - Egypt",  
"44. Cybersecurity Unit - Lesotho",  
"45. Cybersecurity Technical Assistance Team - Zimbabwe",  
"46. Cybercrime and Digital Forensics Unit - Kenya",  
"47. Ministry of ICT and National Guidance - Uganda",  
"48. National Cybersecurity Policy Framework - South Africa",  
"49. Cybersecurity Research and Development Centre - Nigeria",  
"50. Cyber Security Compliance Agency - Malawi",  
"51. Cyber Security Agency - Gabon",  
"52. National Cyber Security and Information Security Committee - Zambia",  
"53. Cybersecurity Capacity Building Office - South Africa",  
"54. Computer Emergency Response Team (CERT) - Rwanda",  
"55. National Cybersecurity Strategy Unit - Cameroon",  
"56. Cybersecurity Risk Management Division - Nigeria",  
"57. Cyber Security Oversight Committee - Uganda",  
"58. Cyber Crime Prevention Unit - Tanzania",  
"59. Cybersecurity Policy Implementation Office - South Africa",  
"60. Cyber Security Assessment Team - Sudan",  
"61. National Cybersecurity Monitoring Centre - Egypt",  
"62. Cyber Security Compliance Office - Zambia",  
"63. National Cybersecurity Action Plan - South Africa",  
"64. Cybersecurity Skills Development Program - Nigeria",  
"65. Cybersecurity Infrastructure Development Division - Kenya",  
"66. Cyber Crime Investigation Bureau - Ethiopia",  
"67. Cyber Security Information Centre - Mali",  
"68. Cybersecurity Advisory Council - Namibia",  
"69. Cybersecurity and Privacy Office - Algeria",  
"70. National Cybersecurity and Information Protection Agency - South Africa",  
"71. Cybersecurity and Incident Response Centre - Seychelles",  
"72. Cybersecurity Governance Committee - Tanzania",  
"73. Cybersecurity Research Institute - Nigeria",  
"74. Cyber Security Incident Management Division - Botswana",  
"75. Cybersecurity Regulatory Agency - Zimbabwe",  
"76. Cybercrime Investigation Agency - Somalia",  
"77. National Cyber Security Framework Implementation Team - Uganda",  
"78. Cyber Security Operations Division - Tunisia",  
"79. Cyber Security Research and Development Institute - South Africa",  
"80. Cybersecurity Awareness Campaign Team - Kenya",  
"81. National Cybersecurity Capacity Building Centre - Ghana",  
"82. Cyber Security Audit and Compliance Division - Nigeria",  
"83. Cyber Security Risk Assessment Unit - Morocco",  
"84. Cyber Security Emergency Response Team - Zambia",  
"85. Cyber Security and Risk Management Agency - Tanzania",  
"86. Cyber Security Awareness and Education Programme - Uganda",  
"87. Cyber Security Coordination Group - South Africa",  
"88. National Cyber Security and Information Sharing Centre - Botswana",  
"89. Cybersecurity Advisory Office - Egypt",  
"90. Cyber Security and Incident Management Unit - Kenya",  
"91. Cyber Crime Prevention Office - Rwanda",  
"92. Cybersecurity Operations Task Force - Zimbabwe",  
"93. Cyber Security Unit - Malawi",  
"94. Cyber Security Governance Framework - Tunisia",  
"95. Cyber Security Research and Awareness Team - Namibia",  
"96. Cyber Security Strategy Development Office - South Africa",  
"97. Cyber Security Compliance and Assurance Office - Zambia",  
"98. National Cybersecurity Stakeholder Forum - Uganda",  
"99. Cybersecurity and Digital Crime Task Force - Algeria",  
"100. Cybersecurity Collaboration and Outreach Division - Nigeria",







// biggest european cyber defence teams


"1. European Union Agency for Cybersecurity (ENISA) - European Union",  
"2. National Cyber Security Centre (NCSC) - United Kingdom",  
"3. Federal Office for Information Security (BSI) - Germany",  
"4. Cyber Security Agency of the Netherlands (NCSC) - Netherlands",  
"5. National Cyber Security Authority (ANSSI) - France",  
"6. Computer Security Incident Response Team (CSIRT) - Spain",  
"7. Cyber Security Division - Belgium",  
"8. National Cybersecurity Centre - Poland",  
"9. National Cyber Security Centre - Ireland",  
"10. Cybersecurity and Infrastructure Security Agency - USA (Europe operations)",  
"11. Cyber Security Agency - Austria",  
"12. Computer Security Incident Response Team (CSIRT) - Italy",  
"13. Swedish Civil Contingencies Agency (MSB) - Sweden",  
"14. National Cyber Security Authority - Denmark",  
"15. Cyber Security Department - Finland",  
"16. National Cyber Security Centre - Norway",  
"17. National Cyber Security Center - Portugal",  
"18. National Cyber Security Centre - Greece",  
"19. National Cybersecurity Agency - Hungary",  
"20. Cyber Security Division - Romania",  
"21. Cyber Security and Incident Response Team - Bulgaria",  
"22. National Cyber Security Authority - Slovakia",  
"23. Cyber Security and Information Assurance - Estonia",  
"24. Computer Emergency Response Team (CERT) - Latvia",  
"25. Cyber Security and Defence Agency - Lithuania",  
"26. National Cyber Security and Defense Center - Czech Republic",  
"27. National Cybersecurity Coordination Centre - Slovenia",  
"28. National Cyber Security Division - Croatia",  
"29. Computer Emergency Response Team (CERT) - Malta",  
"30. National Cyber Security Council - Belgium",  
"31. Cyber Security Operations Centre - Finland",  
"32. National Cyber Security Coordination Centre - Italy",  
"33. Ministry of Digital Affairs - Poland",  
"34. Cyber Security Strategy Implementation Unit - Germany",  
"35. Cyber Security Center - Denmark",  
"36. Cybersecurity Research and Development Centre - Sweden",  
"37. National Cyber Security Strategy Team - Netherlands",  
"38. National Cyber Security and Resilience Authority - Austria",  
"39. Cyber Security Advisory Committee - Ireland",  
"40. National Cyber Security Incident Response Team - Cyprus",  
"41. Cybersecurity and Information Security Agency - Romania",  
"42. Cyber Security Policy Division - Bulgaria",  
"43. National Cybersecurity Strategy Office - Estonia",  
"44. Cyber Security Compliance Office - Norway",  
"45. Cyber Security Threat Intelligence Center - Germany",  
"46. National Cybersecurity Authority - Iceland",  
"47. Cyber Security Incident Management Office - Malta",  
"48. Cyber Security and Forensics Division - Czech Republic",  
"49. Cyber Security and Resilience Office - Slovakia",  
"50. Cyber Security Policy and Planning Unit - Spain",  
"51. Cybersecurity and Data Protection Agency - France",  
"52. National Cybersecurity and Digital Development Committee - Luxembourg",  
"53. Cyber Security Coordination and Strategy Office - Slovenia",  
"54. National Cyber Security Centre for Government - United Kingdom",  
"55. Cyber Security and Data Protection Office - Italy",  
"56. Cybersecurity Compliance Agency - Denmark",  
"57. Cyber Security Training and Awareness Office - Lithuania",  
"58. National Cyber Security and Protection Agency - Latvia",  
"59. Cybersecurity Risk Management Unit - Hungary",  
"60. Cyber Security Operations Division - Portugal",  
"61. National Cyber Security Framework Unit - Croatia",  
"62. Cyber Security and Cyber Defense Agency - Poland",  
"63. Cybersecurity Research Institute - Belgium",  
"64. Cyber Security Information Centre - Romania",  
"65. Cyber Security Strategy Unit - Finland",  
"66. Cyber Security Assurance Division - Greece",  
"67. National Cyber Security Authority - Cyprus",  
"68. Cybersecurity Awareness Campaign Office - Sweden",  
"69. Cyber Security Risk Assessment Division - Netherlands",  
"70. Cybersecurity Development and Training Centre - Italy",  
"71. National Cyber Security Threat Intelligence Bureau - France",  
"72. Cybersecurity Coordination Agency - Slovakia",  
"73. Cyber Security Governance and Compliance Office - Germany",  
"74. Cyber Security Incident Response Division - Ireland",  
"75. National Cyber Security and Incident Management Office - Czech Republic",  
"76. Cyber Security Oversight Committee - Hungary",  
"77. Cybersecurity Resilience Task Force - Belgium",  
"78. Cyber Security Development Office - Finland",  
"79. National Cyber Security Council - Norway",  
"80. Cyber Security and Incident Response Coordination Unit - Malta",  
"81. Cyber Security Training Institute - Greece",  
"82. National Cybersecurity Action Plan Office - Poland",  
"83. Cyber Security Operations and Monitoring Centre - Netherlands",  
"84. Cyber Security Policy Office - Denmark",  
"85. Cyber Security Research and Innovation Office - France",  
"86. Cyber Security Assessment Unit - Lithuania",  
"87. Cybersecurity Strategy Implementation Team - Slovakia",  
"88. Cyber Security and Data Protection Task Force - Portugal",  
"89. National Cyber Security Initiative - Austria",  
"90. Cybersecurity Incident Response and Management Unit - Czech Republic",  
"91. Cyber Security and Digital Resilience Office - Hungary",  
"92. Cyber Security Awareness and Training Office - Estonia",  
"93. Cyber Security Compliance and Assurance Agency - Germany",  
"94. National Cybersecurity and Digital Trust Agency - Sweden",  
"95. Cyber Security Research and Development Bureau - Norway",  
"96. Cyber Security Incident Management Centre - Finland",  
"97. Cyber Security Strategy and Implementation Office - Latvia",  
"98. Cyber Security Awareness and Capacity Building Unit - Romania",  
"99. Cyber Security Risk Management Task Force - Slovenia",  
"100. National Cyber Security Coordination Centre - Belgium",




// biggest north american cyber security companies



"1. CrowdStrike",  
"2. Palo Alto Networks",  
"3. Fortinet",  
"4. McAfee",  
"5. FireEye",  
"6. Check Point Software Technologies",  
"7. NortonLifeLock",  
"8. CyberArk",  
"9. Splunk",  
"10. Trend Micro",  
"11. Cisco Systems",  
"12. IBM Security",  
"13. Proofpoint",  
"14. Rapid7",  
"15. SentinelOne",  
"16. Okta",  
"17. Sophos",  
"18. Vectra AI",  
"19. Zscaler",  
"20. LogRhythm",  
"21. SecureWorks",  
"22. RSA Security",  
"23. Tenable",  
"24. Elastic",  
"25. Diligent",  
"26. Mimecast",  
"27. Netskope",  
"28. Darktrace",  
"29. Cybereason",  
"30. OneLogin",  
"31. Qualys",  
"32. Cylance",  
"33. F5 Networks",  
"34. RiskIQ",  
"35. Illumio",  
"36. A10 Networks",  
"37. Barracuda Networks",  
"38. Sumo Logic",  
"39. Bitdefender",  
"40. Armis",  
"41. Bitglass",  
"42. Attivo Networks",  
"43. Chronicle (Google Cloud)",  
"44. Ping Identity",  
"45. Lacework",  
"46. CyberTAN Technology",  
"47. ESET",  
"48. Tufin",  
"49. Ixia (Keysight Technologies)",  
"50. Alert Logic",  
"51. Everbridge",  
"52. Zix Corporation",  
"53. BeyondTrust",  
"54. SecurityScorecard",  
"55. CyberX",  
"56. RiskLens",  
"57. Cybereason",  
"58. Forcepoint",  
"59. Enveil",  
"60. Menlo Security",  
"61. SecureAuth",  
"62. Cybereason",  
"63. Exabeam",  
"64. BlackBerry",  
"65. Infoblox",  
"66. Malwarebytes",  
"67. Netwrix",  
"68. Sumo Logic",  
"69. Veracode",  
"70. Digital Guardian",  
"71. Cato Networks",  
"72. AppGuard",  
"73. XDR (Extended Detection and Response)",  
"74. Onapsis",  
"75. Cyberint",  
"76. Ordr",  
"77. AppOmni",  
"78. Panaseer",  
"79. Onfido",  
"80. CyCloud",  
"81. Sift",  
"82. Horizon3.ai",  
"83. Guardicore",  
"84. ThreatConnect",  
"85. Tenable",  
"86. Logz.io",  
"87. Pluralsight",  
"88. CyberVista",  
"89. SecurityMetrics",  
"90. SANS Institute",  
"91. CSID (CyberSource Identity Defense)",  
"92. Sumo Logic",  
"93. GuardDuty (AWS)",  
"94. SafeBreach",  
"95. Deroose Technologies",  
"96. Trustwave",  
"97. Deepwatch",  
"98. Cysiv",  
"99. Red Canary",  
"100. 8x8",





    };






    



    


    


    for (int repeat = 0; repeat < 10; repeat++) {
        for (int round = 0; round < 2; round++) {
            for (int i = 0; i < 782; i++) {
                if (good_religious_leaders[i] && national_sec[i]) {
                    printf("%s %s.   please use all security groups into one agi. then lets do 10 = x ,  100 = x , 1000 = x , 10000 = x , 100000 = x , 1000000 = x , 10000000 = x , 100000000 = x , x = good people \n", good_religious_leaders[i], national_sec[i]);
                }
            }
        }
    }

    return 0;
}



